import React, { useState } from "react";
import { X, ShieldCheck, Lock, FileText, CheckCircle, Scale, AlertCircle } from "lucide-react";

interface TermsModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const TermsModal: React.FC<TermsModalProps> = ({ isOpen, onClose }) => {
  const [activeTab, setActiveTab] = useState<"terms" | "privacy">("terms");

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/85 backdrop-blur-md flex items-center justify-center p-4">
      <div className="glass-panel max-w-3xl w-full rounded-2xl border border-slate-800 p-6 sm:p-8 space-y-6 relative max-h-[85vh] overflow-y-auto animate-in fade-in">
        
        {/* Close Button */}
        <button
          onClick={onClose}
          className="absolute top-5 right-5 text-slate-400 hover:text-white transition"
        >
          <X className="w-5 h-5" />
        </button>

        {/* Header */}
        <div className="flex items-center gap-3 border-b border-slate-800 pb-4">
          <div className="w-10 h-10 rounded-xl bg-indigo-600/20 border border-indigo-500/30 flex items-center justify-center text-indigo-400">
            <Scale className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-xl font-bold text-white">
              Terms & Legal Agreements
            </h3>
            <p className="text-xs text-slate-400">
              TalkHir<span className="opacity-75 text-white/90">e</span> User Privacy and Service Guidelines
            </p>
          </div>
        </div>

        {/* Tab Selector */}
        <div className="flex gap-2">
          <button
            onClick={() => setActiveTab("terms")}
            className={`px-4 py-2 rounded-xl text-xs font-semibold transition ${
              activeTab === "terms"
                ? "bg-indigo-600 text-white"
                : "bg-slate-900 text-slate-400 hover:text-white"
            }`}
          >
            Terms & Conditions
          </button>
          <button
            onClick={() => setActiveTab("privacy")}
            className={`px-4 py-2 rounded-xl text-xs font-semibold transition ${
              activeTab === "privacy"
                ? "bg-indigo-600 text-white"
                : "bg-slate-900 text-slate-400 hover:text-white"
            }`}
          >
            Privacy Policy & Data Security
          </button>
        </div>

        {/* Content */}
        <div className="space-y-4 text-xs text-slate-300 leading-relaxed max-h-[50vh] overflow-y-auto pr-2">
          {activeTab === "terms" ? (
            <div className="space-y-4">
              <div className="space-y-1">
                <h4 className="font-bold text-sm text-white">1. Acceptance of Terms</h4>
                <p>
                  By accessing or using the TalkHire platform, you agree to be bound by these Terms and Conditions. TalkHire is designed exclusively as an educational interview simulation and skill enhancement tool for technical candidates.
                </p>
              </div>

              <div className="space-y-1">
                <h4 className="font-bold text-sm text-white">2. Permitted Use</h4>
                <p>
                  You agree to use TalkHire solely for lawful interview practice, career preparation, and personal engineering skill evaluation. You may not attempt to reverse engineer, abuse audio channels, or disrupt the platform's infrastructure.
                </p>
              </div>

              <div className="space-y-1">
                <h4 className="font-bold text-sm text-white">3. AI Evaluation Disclaimer</h4>
                <p>
                  Interview scoring, hiring verdicts, and rubric feedback generated by TalkHire are AI-assisted estimates intended for constructive practice and coaching. They do not guarantee actual hiring decisions or employment offers with any third-party employer.
                </p>
              </div>

              <div className="space-y-1">
                <h4 className="font-bold text-sm text-white">4. Intellectual Property</h4>
                <p>
                  All platform software, user interface designs, simulation flows, and branding associated with TalkHire are the proprietary intellectual property of the founder and platform creators.
                </p>
              </div>
            </div>
          ) : (
            <div className="space-y-4">
              <div className="space-y-1">
                <h4 className="font-bold text-sm text-white">1. Resume & Document Confidentiality</h4>
                <p>
                  Uploaded resumes and pasted job descriptions are processed ephemerally in active memory solely for extracting skill vectors and generating tailored interview probe questions. We never sell, monetize, or share your documents with third-party advertisers.
                </p>
              </div>

              <div className="space-y-1">
                <h4 className="font-bold text-sm text-white">2. Audio & Microphone Data</h4>
                <p>
                  Microphone access is requested strictly to enable real-time speech interaction during your active interview session. Audio streams are encrypted in transit over secure WebRTC connections and are never persisted permanently after your session concludes.
                </p>
              </div>

              <div className="space-y-1">
                <h4 className="font-bold text-sm text-white">3. Scorecard & Transcript Ownership</h4>
                <p>
                  Your performance scorecards, transcripts, and study action plans belong to you. You can export and download them locally at any time upon completing your mock interview.
                </p>
              </div>
            </div>
          )}
        </div>

        {/* Footer Button */}
        <div className="pt-3 border-t border-slate-800 flex justify-end">
          <button
            onClick={onClose}
            className="px-6 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs transition"
          >
            I Understand & Agree
          </button>
        </div>

      </div>
    </div>
  );
};
